my_quotes/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotesapp.urls')),
    path('users/', include('users.urls')),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
        name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html', success_url='/users/reset-password/complete/'),
        name='password_reset_confirm'),
    path('reset-password/complete/', PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
        name='password_reset_complete')
]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm



class LoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())
    
    email = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())

    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())
    
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import LoginForm, RegisterForm
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.views import PasswordResetView
from django.urls import reverse_lazy


def signupuser(request):
    if request.user.is_authenticated:
        return redirect(to='quotesapp:main')

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotesapp:main')
        else:
            return render(request, 'users/signup.html', context={"form": form})

    return render(request, 'users/signup.html', context={"form": RegisterForm()})


def loginuser(request):
    if request.user.is_authenticated:
        return redirect(to='quotesapp:main')

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='users:login')

        login(request, user)
        return redirect(to='quotesapp:main')

    return render(request, 'users/login.html', context={"form": LoginForm()})


@login_required
def logoutuser(request):
    logout(request)
    return redirect(to='quotesapp:main')


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'

users/templates/users/login.html
{% extends "quotesapp/base.html" %}

{% load form_tags %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2 class="text-center mb-4">Login</h2>

            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            {% endif %}

            <form action="{% url 'users:login' %}" method="post" class="p-4 shadow rounded bg-light">
                {% csrf_token %}

                <div class="mb-3">
                    <label for="id_username" class="form-label">Username</label>
                    {{ form.username|add_class:"form-control" }}
                </div>

                <div class="mb-3">
                    <label for="id_password" class="form-label">Password</label>
                    {{ form.password|add_class:"form-control" }}
                </div>

                <div class="d-flex justify-content-between">
                    <button type="submit" class="btn btn-primary, btn-dark">Login</button>
                    <button type="reset" class="btn btn-secondary">Reset</button>
                </div>
                <div class="small text-center">
                    <a href="{% url "users:password_reset" %}" class="text-center">Forgot Password?</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset.html
{% extends "quotesapp/base.html" %}

{% block content %}

<h2>Password reset</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary, btn-dark">Request password reset</button>
</form>

{% endblock %}

users/templates/users/password_reset_complete.html
{% extends "quotesapp/base.html" %}

{% block content %}

    <h2>Password reset complete!</h2>

    <a class="btn btn-primary btn-dark" href="{% url 'users:login' %}">Back</a>

{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends "quotesapp/base.html" %}

{% block content %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary, btn-dark">Save new password</button>
</form>

{% endblock %}

users/templates/users/password_reset_done.html
{% extends "quotesapp/base.html" %}

{% block content %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

<a class="btn btn-primary btn-dark" href="{% url 'users:login' %}">Back</a>

{% endblock %}

users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

users/templates/users/signup.html
{% extends "quotesapp/base.html" %}

{% load form_tags %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2 class="text-center mb-4">Sign Up</h2>

            <form method="post" action="{% url 'users:signup' %}" class="p-4 shadow rounded bg-light">
                {% csrf_token %}

                <div class="mb-3">
                    <label for="id_username" class="form-label">Username</label>
                    {{ form.username|add_class:"form-control" }}
                    <div class="text-danger small">
                        {{ form.errors.username }}
                    </div>
                </div>

                </div class="mb-3">
                    <label for="id_email" class="form-label">Email</label>
                    {{ form.email|add_class:"form-control" }}
                    <div class="text-danger small">
                        {{ form.errors.email }}
                    </div>
                </div>

                <div class="mb-3">
                    <label for="id_password1" class="form-label">Password</label>
                    {{ form.password1|add_class:"form-control" }}
                    <div class="text-danger small">
                        {{ form.errors.password1 }}
                    </div>
                </div>

                <div class="mb-3">
                    <label for="id_password2" class="form-label">Password Confirmation</label>
                    {{ form.password2|add_class:"form-control" }}
                    <div class="text-danger small">
                        {{ form.errors.password2 }}
                    </div>
                </div>

                <div class="d-flex justify-content-between">
                    <button type="submit" class="btn btn-primary, btn-dark">Submit</button>
                    <button type="reset" class="btn btn-secondary">Reset</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}